[package]
name = "rust64"
version = "0.6.0"
authors = [ "Krzysztof Kondrak <krzysztof.kondrak@gmail.com>" ]

[dependencies]
minifb = "0.10"
rand = "0.3.14"
time = "0.1.34"

#[target.'cfg(not(target_os = "redox"))'.dependencies]
#sdl2 = "0.25.0"
